# Generated by Django 5.2.6 on 2025-09-17 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("video_file", models.FileField(upload_to="gallery/videos/")),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="photo",
            old_name="uploaded_at",
            new_name="upload_date",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="album",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="uploaded_by",
        ),
    ]
